# Generated by Django 4.2.5 on 2023-11-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit_of_measurement',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('L', 'Liters')], max_length=50),
        ),
    ]
