# Generated by Django 4.2.7 on 2023-11-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_role_role_userprofile_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='reorder_quantity',
            new_name='min_quantity',
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_of_measurement',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('L', 'Liters'), ('pcs', 'Piece'), ('pack', 'Pack'), ('can', 'Cane')], max_length=50),
        ),
    ]
